# 1. Site Details
site: NBAâ€”Ben Porter
url: https://nba.ben.report
home_url: https://ben.report
title: nba.ben.report
description: nba.ben.report


# 2. Excluded files
exclude:
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - stretch.gemspec
  - .jekyll-cache

# 3. Gems / Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: penborter/stretch-theme

# 4. Gem settings
twitter:
  username: penborter
author: Ben Porter
social:
  name: Ben Porter
  links:
    - https://twitter.com/penborter
    - https://www.linkedin.com/in/penborter
markdown: kramdown

kramdown:
  auto_ids: true

# 5. Jekyll settings
sass:
  style: compressed
timezone: Australia/Sydney #AEST FTW

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page


encoding: utf-8 
lang: en-GB

# 6. Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:slug
  projects:
    output: true
    permalink: /projects/:slug
  stats:
    output: true
    permalink: /stats/:slug

# 7. Site Navigation
nav_header:
- title: Stats
  url: /stats
- title: Posts
  url: /posts
- title: Home
  url: https://ben.report